### ISSUE TITLE
Game crashes upon choosing my custom avatar I made.

### ISSUE THREAD

**Issue by CrispFlake** [StressLevelZero/MarrowSDK#83]
I choose it and when I turn into it the game goes into a blackscreen and closes itself.

**Comment by CrispFlake** [comment]
To add more info, I use the Universal Render Pipeline/Lit (PBR Workflow) shader. I have redone everything about 8 times now and it always happens im literally going insane.

**Comment by Woogoo336** [comment]
I had this issue yesterday. It was a shot in the dark but I fixed it by unconnecting the finger bones from the hand bone. Perhaps check over your rigging and see if there's anything like that going on.

**Comment by CrispFlake** [comment]
So I should just make the finger bones seperate from the hand?

**Comment by Woogoo336** [comment]
"Connected" is a checkbox used in Blender. If they aren't "connected" there's just a dotted lime between the bone and the parent bone. In other words, I made a change so that the finger bones were not touching the end of the hand bone. Could you provide a screenshot of what your hand rigging looks like?

**Comment by Woogoo336** [comment]
No problem. Now that it's confirmed to be the problem it would be useful to note it as a bug report.
